#define MEME_DIR "/home/yincp/Desktop/Descriptor_Preprocessor/src/meme_suite/meme"
#define DATA_DIR "/home/yincp/Desktop/Descriptor_Preprocessor/src/meme_suite/meme/share/meme-5.0.5" 
#define BIN_DIR "/home/yincp/Desktop/Descriptor_Preprocessor/src/meme_suite/meme/bin" 
#define LIBEXEC_DIR "/home/yincp/Desktop/Descriptor_Preprocessor/src/meme_suite/meme/libexec/meme-5.0.5" 
#define TEMP_DIR "" 
