#define MEME_DIR "/Users/melvinyin/Desktop/work/Descriptor_Preprocessor/src/meme_suite/meme"
#define DATA_DIR "/Users/melvinyin/Desktop/work/Descriptor_Preprocessor/src/meme_suite/meme/share/meme-5.0.5" 
#define BIN_DIR "/Users/melvinyin/Desktop/work/Descriptor_Preprocessor/src/meme_suite/meme/bin" 
#define LIBEXEC_DIR "/Users/melvinyin/Desktop/work/Descriptor_Preprocessor/src/meme_suite/meme/libexec/meme-5.0.5" 
#define TEMP_DIR "" 
